doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            user_user_id: 'App\User\Model\Entity\User\IdType'
            user_user_email: 'App\User\Model\Entity\User\EmailType'
            user_user_role: 'App\User\Model\Entity\User\RoleType'
#            comment_comment_id: 'App\Model\Comment\Entity\Comment\IdType'
#            comment_comment_author_id: 'App\Model\Comment\Entity\Comment\AuthorIdType'
#            work_members_group_id: 'App\Model\Work\Entity\Members\Group\IdType'
#            work_members_member_id: 'App\Model\Work\Entity\Members\Member\IdType'
#            work_members_member_email: 'App\Model\Work\Entity\Members\Member\EmailType'
#            work_members_member_status: 'App\Model\Work\Entity\Members\Member\StatusType'
#            work_projects_role_id: 'App\Model\Work\Entity\Projects\Role\IdType'
#            work_projects_role_permissions: 'App\Model\Work\Entity\Projects\Role\PermissionsType'
#            work_projects_project_id: 'App\Model\Work\Entity\Projects\Project\IdType'
#            work_projects_project_status: 'App\Model\Work\Entity\Projects\Project\StatusType'
#            work_projects_project_department_id: 'App\Model\Work\Entity\Projects\Project\Department\IdType'
#            work_projects_task_id: 'App\Model\Work\Entity\Projects\Task\IdType'
#            work_projects_task_type: 'App\Model\Work\Entity\Projects\Task\TypeType'
#            work_projects_task_status: 'App\Model\Work\Entity\Projects\Task\StatusType'
#            work_projects_task_file_id: 'App\Model\Work\Entity\Projects\Task\File\IdType'
#            work_projects_task_change_id: 'App\Model\Work\Entity\Projects\Task\Change\IdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Model/Entity/User'
                prefix: 'App\User\Model\Entity\User'
                alias: User
#            Market:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/ParsingProduct/ParsingProduct/Model/Entity'
#                prefix: 'App\Market\Markets\Model\Entity'
#                alias: ParsingProduct
#            Purchase:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/ParsingProduct/Purchase/Model/Entity'
#                prefix: 'App\Market\Purchases\Model\Entity'
#                alias: Purchase
