controllers:
    resource: ../../src/Controller/
    type: annotation
user_controllers:
    resource: ../../src/User/Controller
    type: annotation
market_controllers:
    resource: ../../src/Markets/Controller
    type: annotation
purchase_controllers:
    resource: ../../src/Purchases/Controller
    type: annotation