controllers:
    resource: ../../src/Controller/
    type: annotation
user_controllers:
    resource: ../../src/User/Controller
    type: annotation
admin_user_controllers:
    resource: ../../src/User/Controller/Admin
    type: annotation
market_controllers:
    resource: ../../src/Market/Markets/Controller
    type: annotation
purchase_controllers:
    resource: ../../src/Market/Purchases/Controller
    type: annotation