<?php
declare(strict_types=1);

namespace App\Tests\User\Entity;

use App\Purchases\Entity\Purchases;
use App\User\Entity\User;
use PHPUnit\Framework\TestCase;

class UserEntityTest extends TestCase
{
    private User $user;

    public function setUp(): void
    {
        $this->user = new User(); // TODO: Change the autogenerated stub
    }

    public function testDefault()
    {
        $this->assertSame(true, $this->user->getIsActive());
    }

    public function testDefaultRole()
    {
        $this->assertContains('ROLE_USER', $this->user->getRoles());
    }

    /** @dataProvider   getSpecificationTests */
    public function testSetRole(string $role)
    {
        $this->user->setRoles([$role]);
        $this->assertContains($role, $this->user->getRoles());
    }

    public function testSetPurchase()
    {
        $this->user->addPurchase($this->createMock(Purchases::class));
        $this->user->addPurchase($this->createMock(Purchases::class));
        $this->assertCount(2, $this->user->getPurchases());
    }

    public function testNotCountPurchases()
    {
        $mock = $this->createMock(Purchases::class);
        $this->user->addPurchase($mock);
        $this->user->addPurchase($mock);
        $this->assertNotCount(2, $this->user->getPurchases());
    }

    public function getSpecificationTests()
    {
        return [
            ['ROLE_ADMIN'],
            ['ROLE_MANAGER'],
            ['ROLE_USER'],
        ];
    }
}